# Generated by Django 4.0.3 on 2022-04-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_contact', models.CharField(max_length=20)),
                ('emp_role', models.CharField(max_length=200)),
                ('emp_salary', models.IntegerField()),
            ],
        ),
    ]
